import { describe, expect, it } from "vitest";
import { aggregate, renderMarkdown, type JournalRecord } from "@tempo/core";

const record = (
  type: JournalRecord["type"],
  data: Record<string, unknown> = {},
  extra: Partial<JournalRecord> = {},
): JournalRecord => ({ ts: "2026-09-03T00:00:00.000Z", type, data, ...extra });

describe("firm report", () => {
  it("aggregates journal facts and scores the estimate closest to settlement", () => {
    const marketId = `0x${"1".repeat(64)}`;
    const tx = `0x${"a".repeat(64)}`;
    const stats = aggregate(
      [
        record("startup", { dryRun: false }),
        record("market-birth", { asset: "BTC" }, { marketId }),
        record("decision", { fairP: 0.55, secondsLeft: 500 }, { agent: "GENESIS", marketId }),
        record("decision", { fairP: 0.8, secondsLeft: 20 }, { agent: "GENESIS", marketId }),
        record("order-sent", { dryRun: false }, { agent: "GENESIS", marketId }),
        record("order-receipt", {}, { agent: "GENESIS", marketId, tx }),
        record("fill", { kind: "BUY_UP" }, { agent: "GENESIS", marketId }),
        record("settlement", { voided: false, winningOutcome: 0 }, { marketId }),
        record("claim", {}, { marketId, tx }),
      ],
      "2026-09-03T00:00:00.000Z",
      "2026-09-03T01:00:00.000Z",
    );

    expect(stats.markets).toEqual({ births: 1, byAsset: { BTC: 1 } });
    expect(stats.execution.orderSends.real).toBe(1);
    expect(stats.execution.uniqueTxHashes).toEqual([tx]);
    expect(stats.estimateQuality.scoredMarkets).toBe(1);
    expect(stats.estimateQuality.brier).toBeCloseTo(0.04);
    expect(stats.estimateQuality.directionalAccuracy).toBe(1);
  });

  it("excludes voided outcomes and reports unavailable scoring honestly", () => {
    const marketId = `0x${"2".repeat(64)}`;
    const stats = aggregate(
      [
        record("decision", { fairP: 0.7, secondsLeft: 15 }, { agent: "VECTOR", marketId }),
        record("settlement", { voided: true }, { marketId }),
      ],
      "2026-09-03T00:00:00.000Z",
      "2026-09-03T01:00:00.000Z",
    );

    expect(stats.estimateQuality.brier).toBeNull();
    expect(stats.estimateQuality.note).toMatch(/UNAVAILABLE/);
    expect(renderMarkdown(stats)).toContain("UNAVAILABLE, not zero");
  });

  it("labels optional generated commentary as an AI narrative", () => {
    const stats = aggregate([], "2026-09-03T00:00:00.000Z", "2026-09-03T01:00:00.000Z");
    const markdown = renderMarkdown(stats, { model: "test-model", text: "No activity was recorded." });

    expect(markdown).toContain("AI NARRATIVE");
    expect(markdown).toContain("generated by test-model");
    expect(markdown).toContain("No activity was recorded.");
  });
});
